export const designPrompts: string[] = [
  "Design a mess token for someone who is late and holding a bag.",
  "Map the system around a shared family phone before you draw a screen.",
  "Design a pharmacy queue ticket that does not require literacy.",
  "Draw twelve conditions of waiting. No apps.",
  "Redesign a college gate pass that assumes luggage.",
  "Write the scene of failure for a clinic waiting room.",
  "Design a receipt for a transaction that should have been a conversation. One page. No brand.",
  "Make a paper service for a kirana shop. No QR.",
  "Design an overdue library slip that tells the student what to do.",
  "Draw the journey of a raindrop on a bus window.",
  "Design a token for a queue you have actually stood in.",
  "Name a constraint that would make your current project honest.",
  "Design for a 70-year-old sharing a phone on a two-bar network.",
  "Sketch an object that lies about its job.",
  "Design a night-shift tool for a security guard. One continuous line first.",
  "Cut ten things from a case study. Keep the argument.",
  "Design a hostel laundry claim without an app.",
  "Make a one-screen intent for a first-year who is lost.",
  "Design a bus depot sign that works in sunlight and panic.",
  "Write five lines of defence: problem, choice, trade-off, evidence, ask.",
  "Design a locker key ritual that does not shame the forgetful.",
  "Map who improvises around a turnstile.",
  "Design a water bottle label for a person who cannot read English.",
  "Make an ugly complete version of a project you have been polishing.",
  "Design a two-queue receptionist desk without a dashboard.",
  "Draw a parent in a pharmacy. Then design.",
  "Design a fine that feels like information, not punishment.",
  "Invent a paper token for a canteen that runs out of the popular dish.",
  "Design for no colour. Then see what remains.",
  "Make a case study opening sentence that contains conflict.",
  "Design a lost-and-found that does not require a WhatsApp group.",
  "Observe a street for twenty minutes. Design one object from the evidence.",
  "Design a timetable that a night-shift worker can actually use.",
  "Replace a hamburger menu with a decision.",
  "Design a complaint form that a vendor with one free hand can finish.",
  "Make eight sketches of the same object under eight constraints.",
  "Design a waiting number that does not jump.",
  "Write who loses if your elegant layout ships.",
  "Design a campus map for someone late to a jury.",
  "Make a service with almost no interface.",
  "Design an ID card that assumes two people might hold it.",
  "Draw the actual path people take, not the designed path.",
  "Design a rain shelter sign for a bus stop that floods.",
  "Name the fake problem in a passion project you have seen.",
  "Design a medicine reminder that does not need a notification.",
  "Make a one-page brief with a job-to-be-done, a constraint, and a success test.",
  "Design a studio booking slip that prevents hoarding.",
  "Sketch a queue that is fair to someone who cannot stand long.",
  "Design a photocopier instruction that survives being photocopied badly.",
  "Write the operating model of a mess. Then design one artefact.",
  "Design a parcel pickup for a hostel with no working lift.",
  "Make a critique card for a project that has gone quiet.",
  "Design a form that refuses ‘other’ as a hiding place.",
  "Draw a security guard’s night. Design one object that would have helped.",
  "Design a voting token for a class election that cannot be duplicated by photocopy.",
  "Make a portfolio project that proves operations, not screens.",
  "Design a silent exam hall instruction.",
  "Map dependencies in a group project. Design the missing handshake.",
  "Design a bicycle parking tag that the monsoon will not destroy.",
  "Write what you would cut if the jury had four minutes.",
  "Design a canteen bill that a table of six can split without an app.",
  "Make a tool for noticing, not for proposing.",
  "Design a first-aid cabinet label for panic.",
  "Draw the hostel corridor at 7am. Design for that noise.",
  "Design a printer queue that tells the truth about time.",
  "Make a project that starts with a constraint on sentence one.",
  "Design a lost ID protocol that does not require the warden’s WhatsApp.",
  "Sketch twelve doors. Only one may use a screen.",
  "Design a scholarship form for a student filling it on a shared phone.",
  "Write evidence that is not a quote from a friend.",
  "Design a lab coat tag that survives a wash.",
  "Make a back-of-house tool for a real café you can visit.",
  "Design a rain check for a photocopy shop that runs out of paper.",
  "Draw a child at a clinic. Design the waiting object.",
  "Design a sports tryout token that cannot be traded.",
  "Make a one-sitting entrance paper for yourself: observe, make, defend.",
  "Design a notice board that does not become wallpaper.",
  "Write who this is actually for, in a room, on a day.",
  "Design a bicycle bell instruction for a campus that bans horns.",
  "Make a roast of your own case study using one wound: no decision, no user, or no ending.",
  "Design a tap that tells you the water will stop.",
  "Map a kirana credit notebook. Do not digitise it until you understand it.",
  "Design a late-entry pass that is not humiliation.",
  "Draw an umbrella for a guard on a night shift.",
  "Design a group project contract that names the cut.",
  "Make a prompt you would actually finish in two hours.",
  "Design a staircase sign for a fire drill that people ignore.",
  "Write the crime: intended use versus actual use.",
  "Design a meal skip token that does not waste food.",
  "Make a decision tool for the next portfolio project — then stop adding projects.",
  "Design a bench plaque that a tired parent can read.",
  "Sketch a ticket that works when the printer is down.",
  "Design a critique format for a jury of three with twelve minutes.",
  "Make an artefact that can be shown, not a process wall.",
  "Design a water cooler queue without a rope.",
  "Write one practice instruction for how your brain actually works.",
  "Design a studio light switch that the last person cannot forget.",
  "Make a pack of ten dares that refuse ‘redesign the app’.",
  "Design the smallest object that proves you understood the problem.",
  "Open the list again tomorrow. Pick by number. Finish or abandon.",
];

if (designPrompts.length !== 100) {
  throw new Error(`Expected 100 prompts, got ${designPrompts.length}`);
}
